//! CAVP (Cryptographic Algorithm Validation Program) test vector
//! generation.
//!
//! FIPS validation requires running the NIST CAVP tool against
//! known-answer test vectors. The tool takes `.req` (request) files
//! in a specific format and produces `.rsp` (response) files. The
//! `.rsp` is then compared to the output of the module-under-test.
//!
//! ## What this module does
//!
//! We don't run the CAVP tool here (it requires a NIST-issued
//! tool). We **generate the `.req` files** in the format the
//! tool expects. The lab runs the tool, our code computes the
//! same input, and we ship the `.rsp` files alongside our code
//! for the lab to compare.
//!
//! ## Caveat
//!
//! The `.rsp` files we generate are based on our internal
//! `ring`-backed implementation. They would be used as a baseline
//! for the lab's CAVP run; the lab will run the CAVP tool against
//! their reference and compare to ours. The lab may also have
//! their own test vectors that we re-run.
//!
//! ## File format
//!
//! The CAVP format is plain text with sections delimited by
//! headers like `[ENCRYPT]`, `[DECRYPT]`, `[HASH]`, etc. Each
//! section has `COUNT = N` followed by `KEY = ...`, `IV = ...`,
//! etc., and one block per test case. We emit the standard
//! CAVS 21.A / AES / GCM / SHA2 / HMAC / PBKDF2 formats.

use std::fmt::Write as _;
use std::path::Path;

/// Generate a CAVP request file for AES-256-GCM (encrypt direction).
///
/// `count` is the number of test cases to include.
pub fn cavp_aes_gcm_encrypt(count: u32) -> String {
    let mut out = String::new();
    out.push_str("# CAVP AES-256-GCM test vectors (encrypt)\n");
    out.push_str("# Generated by Soteria FIPS module\n\n");
    out.push_str("[ENCRYPT]\n");
    out.push_str("COUNT = 0\n");
    for i in 0..count {
        // Use a deterministic test pattern so the lab can reproduce.
        let key = format!("{:064x}", i);
        let iv = format!("{:024x}", i);
        let pt = format!("{:016x}", i); // 8-byte plaintexts
        let aad = format!("{:016x}", i);
        writeln!(out, "COUNT = {i}").unwrap();
        writeln!(out, "KEY = {key}").unwrap();
        writeln!(out, "IV = {iv}").unwrap();
        writeln!(out, "AAD = {aad}").unwrap();
        writeln!(out, "PLAINTEXT = {pt}").unwrap();
        out.push('\n');
    }
    out
}

/// Generate a CAVP request file for SHA-256.
pub fn cavp_sha256(count: u32) -> String {
    let mut out = String::new();
    out.push_str("# CAVP SHA-256 test vectors\n");
    out.push_str("# Generated by Soteria FIPS module\n\n");
    out.push_str("[HASH]\n");
    for i in 0..count {
        let msg = format!("{:08x}", i);
        let len = msg.len() * 4; // bits
        writeln!(out, "COUNT = {i}").unwrap();
        writeln!(out, "LEN = {len}").unwrap();
        writeln!(out, "MSG = {msg}").unwrap();
        out.push('\n');
    }
    out
}

/// Generate a CAVP request file for HMAC-SHA-256.
pub fn cavp_hmac_sha256(count: u32) -> String {
    let mut out = String::new();
    out.push_str("# CAVP HMAC-SHA-256 test vectors\n");
    out.push_str("# Generated by Soteria FIPS module\n\n");
    out.push_str("[HMAC-SHA-256]\n");
    for i in 0..count {
        let key = format!("{:064x}", i); // 32-byte key
        let msg = format!("{:016x}", i); // 8-byte message
        let key_len = key.len() * 4;
        let msg_len = msg.len() * 4;
        writeln!(out, "COUNT = {i}").unwrap();
        writeln!(out, "KEY = {key}").unwrap();
        writeln!(out, "KEYLEN = {key_len}").unwrap();
        writeln!(out, "MSG = {msg}").unwrap();
        writeln!(out, "MSGLEN = {msg_len}").unwrap();
        out.push('\n');
    }
    out
}

/// Generate a CAVP request file for PBKDF2-HMAC-SHA-256.
pub fn cavp_pbkdf2_sha256(count: u32) -> String {
    let mut out = String::new();
    out.push_str("# CAVP PBKDF2-HMAC-SHA-256 test vectors\n");
    out.push_str("# Generated by Soteria FIPS module\n\n");
    out.push_str("[PBKDF2]\n");
    out.push_str("Hash = SHA256\n");
    for i in 0..count {
        let pw = format!("{:08x}", i);
        let salt = format!("{:016x}", i);
        let iter = 1000 + i * 100;
        let dklen = 32;
        writeln!(out, "COUNT = {i}").unwrap();
        writeln!(out, "P = {pw}").unwrap();
        writeln!(out, "S = {salt}").unwrap();
        writeln!(out, "c = {iter}").unwrap();
        writeln!(out, "dkLen = {dklen}").unwrap();
        out.push('\n');
    }
    out
}

/// Write all CAVP request files to a directory.
pub fn write_cavp_files(dir: &Path, count: u32) -> std::io::Result<()> {
    std::fs::create_dir_all(dir)?;
    std::fs::write(
        dir.join("AES_256_GCM_encrypt.req"),
        cavp_aes_gcm_encrypt(count),
    )?;
    std::fs::write(dir.join("SHA256.req"), cavp_sha256(count))?;
    std::fs::write(dir.join("HMAC_SHA256.req"), cavp_hmac_sha256(count))?;
    std::fs::write(dir.join("PBKDF2_SHA256.req"), cavp_pbkdf2_sha256(count))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn cavp_files_written() {
        let dir = tempdir().unwrap();
        write_cavp_files(dir.path(), 5).unwrap();
        let aes = std::fs::read_to_string(dir.path().join("AES_256_GCM_encrypt.req")).unwrap();
        assert!(aes.contains("[ENCRYPT]"));
        let sha = std::fs::read_to_string(dir.path().join("SHA256.req")).unwrap();
        assert!(sha.contains("[HASH]"));
        let pbkdf2 = std::fs::read_to_string(dir.path().join("PBKDF2_SHA256.req")).unwrap();
        assert!(pbkdf2.contains("Hash = SHA256"));
    }
}
