//! Software/Firmware Integrity Test (SFIT).
//!
//! FIPS 140-3 mandates that the module perform an integrity test
//! at startup: a MAC (HMAC-SHA-256) over the loaded binary, compared
//! to a value embedded at build time. If the binary has been
//! tampered with, the integrity test fails and the module refuses
//! to start.
//!
//! ## How this works in practice
//!
//! - **At build time**: a `build.rs` script computes the
//!   HMAC-SHA-256 of the freshly compiled binary using a
//!   build-time secret (a "Module Integrity Key" generated by the
//!   build environment, or a key the user supplies via env var).
//!   The result is stored in a separate file
//!   `target/soteria-module.hmac`.
//! - **At runtime**: the integrity test reads the binary, computes
//!   the same HMAC, and compares to the expected value. If they
//!   match, the binary is unchanged.
//!
//! ## The build-time vs runtime key problem
//!
//! Strictly, the FIPS validation requires that the integrity key
//! not be modifiable by the user. We support two modes:
//! - **Build mode** (default for development): the build generates
//!   a random key, embeds the HMAC, and the runtime key is a
//!   constant in the binary. This is a soft FIPS mode and will
//!   be flagged by the lab for a real submission.
//! - **Signed mode** (for production): the build signs the binary
//!   with a private key held by the operator. The runtime
//!   holds the public key (e.g., in a TPM NVRAM or in the binary
//!   itself). This is the FIPS-compliant mode.
//!
//! In this MVP, we ship the **build mode** and document the
//! signed-mode gap in the security policy.

use super::primitives::hmac_sha256;
use std::path::Path;

/// The build-time Module Integrity Key. In build mode this is a
/// hard-coded constant; the HMAC of the binary + this key is
/// expected at runtime. In a real FIPS submission, this constant
/// would be derived from a private key held outside the binary.
///
/// This is intentionally public (in the source) for the MVP —
/// the security policy flags it as "FIPS-DEV-MODE; not for
/// production FIPS validation".
pub const BUILD_MODE_INTEGRITY_KEY: &[u8; 32] = b"sot-fips-140-3-dev-mode-key--v1.";

/// The path to the HMAC file written by the build script.
pub const HMAC_FILE_PATH: &str = "target/soteria-module.hmac";

/// Result of an integrity test.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum IntegrityResult {
    /// Integrity test passed; binary is unchanged.
    Pass,
    /// No HMAC file found (probably a non-build-mode install).
    NoHmacFile,
    /// The HMAC of the running binary does not match the expected.
    /// The binary has been tampered with.
    Mismatch,
    /// I/O error reading the binary or HMAC file.
    IoError(String),
}

/// Run the integrity test. `binary_path` is the path to the running
/// binary. `expected_hmac_path` is the path to the file containing
/// the expected HMAC (one line: 64 hex chars).
pub fn run_integrity_test(binary_path: &Path) -> IntegrityResult {
    let expected = match std::fs::read_to_string(HMAC_FILE_PATH) {
        Ok(s) => s.trim().to_string(),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return IntegrityResult::NoHmacFile,
        Err(e) => return IntegrityResult::IoError(e.to_string()),
    };
    let binary = match std::fs::read(binary_path) {
        Ok(b) => b,
        Err(e) => return IntegrityResult::IoError(e.to_string()),
    };
    let actual = hmac_sha256(BUILD_MODE_INTEGRITY_KEY, &binary);
    let actual_hex = hex::encode(actual);
    if actual_hex == expected {
        IntegrityResult::Pass
    } else {
        IntegrityResult::Mismatch
    }
}

/// Compute the integrity HMAC of a binary. Used by the build script.
pub fn compute_integrity_hmac(binary: &[u8]) -> [u8; 32] {
    hmac_sha256(BUILD_MODE_INTEGRITY_KEY, binary)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn integrity_roundtrip() {
        let dir = tempdir().unwrap();
        let bin = dir.path().join("soteriad.bin");
        let fake_binary = b"this is the binary content";
        std::fs::write(&bin, fake_binary).unwrap();

        // Compute the expected HMAC.
        let expected = compute_integrity_hmac(fake_binary);
        std::fs::write(HMAC_FILE_PATH, hex::encode(expected)).unwrap();

        // Run the integrity test.
        // We can't easily change the global HMAC_FILE_PATH at
        // test time, so we just verify the helper function.
        assert_eq!(compute_integrity_hmac(fake_binary), expected);
    }
}
