# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra", "~> 4.1"
gem "sinatra-contrib", "~> 4.1"
gem "puma", "~> 6.5"
gem "erubi", "~> 1.13"
gem "json", "~> 2.9"
gem "net-http", "~> 0.4"
gem "uri", "~> 0.13"
gem "rackup", "~> 2.2"

group :development do
  gem "rerun", "~> 0.14"
  gem "pry", "~> 0.14"
end

group :test do
  gem "minitest", "~> 5.25"
  gem "rack-test", "~> 2.1"
end
